apiVersion: 1

datasources:
  - name: Prometheus
    uid: usslp-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
    editable: false

  - name: Jaeger
    uid: usslp-jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
