/*
 * usslp_canon.h - the USSLP price attestation canonical encoding, in C.
 *
 * This is a byte-for-byte port of AttestationInput.CanonicalString in
 * platform/pkg/canon/attestation.go. It is the single most correctness-critical
 * file in this firmware.
 *
 * If this encoding and the Go one disagree by one character, every label in the
 * fleet computes a digest that does not match the one the platform signed, the
 * verifier refuses the update, and the label keeps showing yesterday's price —
 * correctly, quietly, and forever. There is no telemetry signature that
 * distinguishes "the platform is being tampered with" from "the firmware's
 * encoder has an off-by-one in its RFC 3339 formatter". So the port is
 * deliberately literal, and firmware/tests/test_canon.c drives it with vectors
 * generated by running the Go implementation.
 *
 * The encoding, for reference:
 *
 *   usslp.price.v1|<tenant>|<store>|<label>|<sku>|<amount_minor>|<currency>|
 *   <RFC3339 UTC to the second>|<sequence>|<promotion>
 *
 * with no whitespace, no optional fields, integer minor units, and the
 * timestamp always rendered as UTC with a literal 'Z'. Go's time.RFC3339 layout
 * carries no fractional seconds, so a caller's sub-second precision is dropped
 * on both sides — that is why the input here is whole seconds since the epoch
 * rather than anything richer.
 */

#ifndef USSLP_CANON_H
#define USSLP_CANON_H

#include "../usslp_portable.h"
#include "usslp_sha256.h"

/* canon.ValidID caps an identifier at 128 bytes. Five identifiers, an int64
 * amount (20 bytes with sign), a three-byte currency, a 20-byte timestamp, an
 * int64 sequence (20 bytes), the 14-byte scheme tag and nine separators:
 *
 *   14 + 9 + 5*128 + 20 + 3 + 20 + 20 = 726
 *
 * rounded up to 768 for the NUL and for headroom against a future field. */
#define USSLP_CANON_MAX_ID 128
#define USSLP_CANON_MAX_LEN 768

/* The scheme tag. Changing it is a wire break and must be coordinated with
 * platform/pkg/canon; the constant is spelled out here rather than derived so
 * that a grep for the literal finds both ends. */
#define USSLP_CANON_SCHEME "usslp.price.v1"

/* usslp_price_input is the tuple that is signed. Every field that could change
 * what a shopper is charged is here, and nothing else is — re-rendering with a
 * different template must not invalidate an attestation. */
struct usslp_price_input {
	const char *tenant;    /* canon.TenantID */
	const char *store;     /* canon.StoreID */
	const char *label;     /* canon.LabelID */
	const char *sku;       /* canon.SKU */
	int64_t amount_minor;  /* canon.Money.Amount, minor units, may be negative */
	const char *currency;  /* canon.Money.Currency, ISO 4217 alphabetic, upper case */
	int64_t effective_at;  /* seconds since the Unix epoch, UTC, may be negative */
	int64_t sequence;      /* canon.PriceUpdated.Sequence */
	const char *promotion; /* canon.PromotionID, may be empty but never NULL */
};

/*
 * usslp_canon_price_string renders the canonical string into out.
 *
 * Returns USSLP_OK and sets *out_len to the length excluding the NUL, or
 * USSLP_ERR_NOSPACE if cap is too small, or USSLP_ERR_INVAL if a field is NULL,
 * over-long, or the timestamp falls outside the years 0000-9999 that a
 * four-digit RFC 3339 year can represent.
 *
 * The label itself only needs the digest, and usslp_canon_price_digest below
 * computes it without materialising the string. This entry point exists for the
 * host tests — which compare the bytes against the Go output directly, not just
 * the hash of them — and for the diagnostic shell command a field engineer uses
 * when a label is refusing prices and nobody knows why.
 */
int usslp_canon_price_string(const struct usslp_price_input *in, char *out, size_t cap,
			     size_t *out_len);

/*
 * usslp_canon_price_digest computes SHA-256 over the canonical string without
 * building it, by feeding each field to the hash as it is produced.
 *
 * This is the path the price handler actually takes. It keeps a 726-byte
 * worst-case buffer off a thread stack that is otherwise 1 KiB, and it means
 * the largest transient the verifier needs is the 104-byte SHA-256 context.
 * test_canon.c asserts that this function and
 * usslp_sha256(usslp_canon_price_string(...)) agree on every vector, so the
 * optimisation cannot silently drift away from the string it claims to hash.
 */
int usslp_canon_price_digest(const struct usslp_price_input *in,
			     uint8_t digest[USSLP_SHA256_DIGEST_LEN]);

/*
 * usslp_canon_format_i64 writes a base-10 int64 exactly as Go's
 * strconv.FormatInt does: a leading '-' for negatives, no '+', no padding, and
 * "0" for zero. Returns the number of bytes written, or 0 if cap is too small.
 * cap must be at least 21 to be safe for every input including INT64_MIN.
 */
size_t usslp_canon_format_i64(int64_t v, char *out, size_t cap);

/*
 * usslp_canon_format_rfc3339_utc writes exactly 20 bytes:
 * "YYYY-MM-DDTHH:MM:SSZ", which is what
 * time.Unix(sec,0).UTC().Format(time.RFC3339) produces for any second-precision
 * instant in the supported year range. Returns 20, or 0 if cap < 21 or the year
 * is outside 0..9999.
 */
size_t usslp_canon_format_rfc3339_utc(int64_t unix_seconds, char *out, size_t cap);

#endif /* USSLP_CANON_H */
